#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: eclipse-repo-build
  namespace: galasa-tekton
spec:
  workspaces:
  - name: git-workspace
    optional: false
  params:
  - name: distBranch
    type: string
  - name: refspec
    type: string
  - name: noPush
    type: string
    default: ""
  tasks:
  - name: clone-eclipse
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/eclipse
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "9999999"
    - name: subdirectory
      value: eclipse
    workspaces:
     - name: output
       workspace: git-workspace
  - name: eclipse-build
    taskRef:
      name: eclipse-repo-build
    runAfter:
    - clone-eclipse
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: eclipseRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/photon/
    - name: simplatformSourceRepo
      value: https://galasadev-cicsk8s.hursley.ibm.com/main/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://galasadev-cicsk8s.hursley.ibm.com/$(params.distBranch)/maven/obr/
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-eclipse-maven
    taskRef:
      name: recycle-deployment
    runAfter:
    - eclipse-build
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: maven-$(params.distBranch)-eclipse
  - name: recycle-eclipse-p2
    taskRef:
      name: recycle-deployment
    runAfter:
    - eclipse-build
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: p2-$(params.distBranch)
